# Assignment #03
1. Explore College Scorecard website - https://collegescorecard.ed.gov/ 

2. Explore College Scorecard Data web page - https://collegescorecard.ed.gov/data/

3. Download and skim the documentation - https://collegescorecard.ed.gov/assets/FullDataDocumentation.pdf

4. Download the dataset - https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data.zip (265MB Zip File)

5. Unzip the file into a folder (there are many files, one for each school year)

6. Import the 2017-2018 school year file "MERGED2017_18_PP.csv" and explore:   

    * how many colleges or rows?   

    * how many variables or columns?   

    * Look at the first 20 rows   

    * look at the last 20 rows   

    * Look at a random sample of 20 rows    

7. Since there are too many variables to explore, many of which are not interesting. Modify your import statement to only import the following 9 variables:

- UNITID
- INSTNM
- CITY
- STABBR
- ZIP
- ADM_RATE
- UGDS
- TUITIONFEE_IN
- MN_EARN_WNE_P10 

8. Download and read the data dictionary file - https://collegescorecard.ed.gov/assets/CollegeScorecardDataDictionary.xlsx

Find out the definition of the above 9 variables and document the definitions in the Jupyter Notebook so that the readers will not need to repeat what you have done to know the meaning of these variables.

9. Use the predefined cells below to conduct and document your data exploration.

When in doubt, Google. Find examples and read documents/tutorials. 

Have fun!

In [1]:
# Import libraries
import pandas as pd
#(Write code here)

In [3]:
# load the 2017-2018 school year file "MERGED2017_18_PP.csv" 

#loading data into pandas
dataframe=pd.read_csv("MERGED2017_18_PP.csv")
#dataframe.head(2)
#(Write code here)

In [8]:
# Find out how many colleges or rows?   
# Find out how many variables or columns? 
#(Write code here)

#for printing number of rows and columns in the format of (rows,columns)
rows_columns= dataframe.shape

#for printing number of rows
rows=len(dataframe.index)

#for printing number of columns
columns = len(dataframe.columns)

print("The number of rows are:", rows)
print("The number of columns are:", columns)
print("number of rows and columns in the format of (rows,columns) are",rows_columns)

The number of rows are: 7112
The number of columns are: 1977
number of rows and columns in the format of (rows,columns) are (7112, 1977)

In [9]:
# Look at the first 20 rows  
#(Write code here)

#printing the first 20 rows of the dataframe 
first20=dataframe.head(20)
print(first20)

    UNITID    OPEID  OPEID6                                     INSTNM  \
0   100654   100200    1002                   Alabama A & M University
1   100663   105200    1052        University of Alabama at Birmingham
2   100690  2503400   25034                         Amridge University
3   100706   105500    1055        University of Alabama in Huntsville
4   100724   100500    1005                   Alabama State University
5   100751   105100    1051                  The University of Alabama
6   100760   100700    1007          Central Alabama Community College
7   100812   100800    1008                    Athens State University
8   100830   831000    8310            Auburn University at Montgomery
9   100858   100900    1009                          Auburn University
10  100937   101200    1012                Birmingham Southern College
11  101028  1218200   12182     Chattahoochee Valley Community College
12  101073  1055400   10554                  Concordia College Alabama
13  101116  1303906   13039                South University-Montgomery
14  101143   101500    1015         Enterprise State Community College
15  101161   106000    1060          Coastal Alabama Community College
16  101189   100300    1003                        Faulkner University
17  101240   101700    1017            Gadsden State Community College
18  101277  4187200   41872       New Beginning College of Cosmetology
19  101286   101800    1018  George C Wallace Community College-Dothan

              CITY STABBR         ZIP  \
0           Normal     AL       35762
1       Birmingham     AL  35294-0110
2       Montgomery     AL  36117-3553
3       Huntsville     AL       35899
4       Montgomery     AL  36104-0271
5       Tuscaloosa     AL  35487-0166
6   Alexander City     AL       35010
7           Athens     AL       35611
8       Montgomery     AL  36117-3596
9           Auburn     AL       36849
10      Birmingham     AL       35254
11     Phenix City     AL       36869
12           Selma     AL       36701
13      Montgomery     AL       36116
14      Enterprise     AL  36330-1300
15     Bay Minette     AL  36507-2698
16      Montgomery     AL  36109-3390
17         Gadsden     AL       35903
18     Albertville     AL       35951
19          Dothan     AL  36303-9234

                                         ACCREDAGENCY  \
0   Southern Association of Colleges and Schools C...
1   Southern Association of Colleges and Schools C...
2   Southern Association of Colleges and Schools C...
3   Southern Association of Colleges and Schools C...
4   Southern Association of Colleges and Schools C...
5   Southern Association of Colleges and Schools C...
6   Southern Association of Colleges and Schools C...
7   Southern Association of Colleges and Schools C...
8   Southern Association of Colleges and Schools C...
9   Southern Association of Colleges and Schools C...
10  Southern Association of Colleges and Schools C...
11  Southern Association of Colleges and Schools C...
12                                                NaN
13  Southern Association of Colleges and Schools C...
14  Southern Association of Colleges and Schools C...
15  Southern Association of Colleges and Schools C...
16  Southern Association of Colleges and Schools C...
17  Southern Association of Colleges and Schools C...
18  National Accrediting Commission of Career Arts...
19  Southern Association of Colleges and Schools C...

                                              INSTURL  \
0                                       www.aamu.edu/
1                                         www.uab.edu
2                           www.amridgeuniversity.edu
3                                         www.uah.edu
4                                       www.alasu.edu
5                                         www.ua.edu/
6                                        www.cacc.edu
7                                      www.athens.edu
8                                         www.aum.edu
9                                      www.auburn.edu
10                                       www.bsc.edu/
11                                         www.cv.edu
12                                      www.ccal.edu/
13  www.southuniversity.edu/montgomery#location=Mo...
14                                       www.escc.edu
15                             www.coastalalabama.edu
16                                   www.faulkner.edu
17                               www.gadsdenstate.edu
18                             www.nbccosmetology.com
19                                    www.wallace.edu

                                               NPCURL  ...  \
0   https://galileo.aamu.edu/NetPriceCalculator/np...  ...
1            uab.studentaidcalculator.com/survey.aspx  ...
2                    www2.amridgeuniversity.edu:9091/  ...
3                                     finaid.uah.edu/  ...
4   www.alasu.edu/cost-aid/forms/calculator/index....  ...
5           financialaid.ua.edu/net-price-calculator/  ...
6          https://www.cacc.edu/net-price-calculator/  ...
7   https://24.athens.edu/apex/prod8/f?p=174:1:394...  ...
8   www.aum.edu/current-students/financial-informa...  ...
9   https://www.auburn.edu/admissions/costcalc/fre...  ...
10                   www.bsc.edu/fp/np-calculator.cfm  ...
11             www.cv.edu/about/consumer-information/  ...
12    www.ccal.edu/admissions/net-pricing-calculator/  ...
13  www.southuniversity.edu/montgomery/net-price-c...  ...
14           https://www.escc.edu/netprice/npcalc.htm  ...
15                             www.coastalalabama.edu  ...
16        www.faulkner.edu/net-price-calculator-form/  ...
17          www.gadsdenstate.edu/net-price-calculator  ...
18                 nbccosmetology.com/sa/nbc_zonemap/  ...
19          www.wallace.edu/net_price_calculator.aspx  ...

    OMAWDP8_NOTFIRSTTIME_POOLED_SUPP  OMENRUP_NOTFIRSTTIME_POOLED_SUPP  \
0                             0.4048                            0.2645
1                             0.5448                              0.12
2                             0.4647                            0.1912
3                             0.5121                            0.1593
4                             0.4226                            0.0754
5                             0.6376                            0.1267
6                             0.2807                            0.3502
7                             0.5627                            0.2276
8                             0.4884                            0.2048
9                             0.7038                             0.072
10                            0.6196                            0.0326
11                            0.2463                            0.1667
12                            0.0957                             0.505
13                            0.2574                            0.6426
14                             0.283                            0.3396
15                             0.297                            0.0998
16                            0.5333                            0.1701
17                            0.2818                            0.5138
18                               NaN                               NaN
19                            0.3583                             0.294

    OMENRYP_FULLTIME_POOLED_SUPP  OMENRAP_FULLTIME_POOLED_SUPP  \
0                         0.0137                         0.315
1                         0.0728                        0.2583
2                         0.0148                        0.3284
3                         0.0165                         0.323
4                         0.0254                        0.5327
5                         0.0073                        0.2431
6                         0.0142                        0.3794
7                         0.0109                        0.1797
8                         0.0134                        0.4208
9                         0.0062                        0.2026
10                        0.0031                        0.3303
11                        0.0155                        0.5959
12                         0.006                        0.2376
13                             0                        0.1263
14                        0.0095                        0.3663
15                        0.0119                        0.5981
16                        0.0057                        0.3406
17                        0.0215                        0.1641
18                           NaN                           NaN
19                        0.0221                        0.2986

    OMAWDP8_FULLTIME_POOLED_SUPP  OMENRUP_FULLTIME_POOLED_SUPP  \
0                         0.3755                        0.2958
1                         0.5872                        0.0817
2                         0.4391                        0.2177
3                         0.5361                        0.1243
4                         0.3133                        0.1286
5                         0.6817                        0.0679
6                         0.2206                        0.3858
7                          0.649                        0.1604
8                          0.327                        0.2388
9                         0.7405                        0.0506
10                        0.6319                        0.0348
11                        0.2216                         0.167
12                        0.1037                        0.6526
13                        0.2184                        0.6553
14                        0.3104                        0.3138
15                        0.2845                        0.1056
16                        0.4638                          0.19
17                        0.2742                        0.5402
18                           NaN                           NaN
19                        0.2993                        0.3799

    OMENRYP_PARTTIME_POOLED_SUPP  OMENRAP_PARTTIME_POOLED_SUPP  \
0                         0.0289                        0.4224
1                         0.1398                        0.2618
2                          0.028                        0.3645
3                         0.0245                        0.3947
4                          0.021                        0.5804
5                         0.0142                        0.2842
6                         0.0092                        0.3258
7                         0.0181                        0.2112
8                         0.0289                        0.3737
9                         0.0143                        0.3829
10                           NaN                           NaN
11                        0.0067                        0.5705
12                             0                        0.2075
13                        0.0035                        0.0804
14                         0.004                        0.4113
15                         0.019                        0.5704
16                        0.0112                        0.3825
17                        0.0835                        0.1191
18                           NaN                           NaN
19                         0.043                        0.2557

    OMAWDP8_PARTTIME_POOLED_SUPP  OMENRUP_PARTTIME_POOLED_SUPP
0                         0.2635                        0.2852
1                         0.3977                        0.2008
2                         0.4486                        0.1589
3                         0.3476                        0.2331
4                         0.1678                        0.2308
5                         0.4599                        0.2416
6                         0.2769                        0.3881
7                         0.4741                        0.2966
8                         0.2352                        0.3622
9                         0.4571                        0.1457
10                           NaN                           NaN
11                        0.1678                         0.255
12                        0.0094                         0.783
13                        0.2308                        0.6853
14                        0.1707                         0.414
15                        0.2838                        0.1268
16                        0.3582                        0.2481
17                        0.2338                        0.5636
18                           NaN                           NaN
19                        0.2743                         0.427

[20 rows x 1977 columns]

In [10]:
# Look at the last 20 rows 
#(Write code here)

#printing the last 20 rows of the dataframe
dataframe.tail(20)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
7092,47503311,4208611,42086,Relay Graduate School of Education - San Antonio,San Antonio,TX,782155155,Middle States Commission on Higher Education,relay.edu/location/relay-san-antonio,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7093,47503312,4208612,42086,Relay Graduate School of Education - Dallas-Fo...,Dallas,TX,752075155,Middle States Commission on Higher Education,relay.edu/location/relay-dallas-fort-worth,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7094,47503313,4208613,42086,Relay Graduate School of Education - Washingto...,Washington,DC,200375155,Middle States Commission on Higher Education,relay.edu/location/relay-washington-dc,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7095,47647001,4088301,40883,WestMed College - Merced,Merced,CA,953400000,NaN,www.westmedcollege.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7096,47662901,4189101,41891,Salon Institute - Columbus Campus,Lewis Center,OH,430359153,National Accrediting Commission of Career Arts...,www.saloninstitute.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7097,47691101,4205801,42058,SAE Institute of Technology San Francisco,Emeryville,CA,94608,NaN,usa.sae.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7098,48065701,869423,8694,Rasmussen College - Overland Park,Overland Park,KS,662102786,Higher Learning Commission,rasmussen.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7099,48079001,4218901,42189,Rocky Vista University - Southern Utah,Ivins,UT,847386756,Higher Learning Commission,www.rvu.edu/rvu-su/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7100,48092101,4220001,42200,Designer Barber & Stylist School -,Springdale,AR,727620990,National Accrediting Commission of Career Arts...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7101,48133101,4213501,42135,Sharp Edgez Barber Institute - Buffalo,Buffalo,NY,142170000,Council on Occupational Education,www.sharpedgezbarberinstitute.com,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7102,48154401,4220901,42209,National Personal Training Institute of Cleveland,Highland Heights,OH,44143,Accrediting Council for Continuing Education &...,nptiohio.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7103,48305401,4224601,42246,Barber School of Pittsburgh - Ambridge,Ambridge,PA,150030000,NaN,www.bsp.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7104,48312401,108131,1081,Arizona State University at Tucson,Tucson,AZ,857454284,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7105,48312402,108161,1081,Arizona State University - ASU Colleges at Lak...,Lake Havasu City,AZ,864036877,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7106,48312403,108162,1081,Arizona State University at The Gila Valley,Thatcher,AZ,855525545,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7107,48312404,108163,1081,Arizona State University at Yuma,Yuma,AZ,853656900,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7108,48387801,4223701,42237,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,95113,Accrediting Council for Independent Colleges a...,www.bamasf.com/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7109,48400201,4228101,42281,High Desert Medical College,Lancaster,CA,935340000,Accrediting Council for Continuing Education &...,www.hdmc.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7110,48778201,4221501,42215,BCI - Malden,Malden,MA,021480000,NaN,bostoncareer.org,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7111,49005401,4182601,41826,Health Career Institute- Lauderdale Lakes,Lauderdale Lakes,FL,333137268,Accrediting Commission of Career Schools and C...,www.hci.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Look at a random sample of 20 rows    
#(Write code here)

#randomly generating 20 rows from the dataframe
dataframe.sample(n =20)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
3560,229115,364400,3644,Texas Tech University,Lubbock,TX,79409-5005,Southern Association of Colleges and Schools C...,www.ttu.edu,www.depts.ttu.edu/financialaid/netCostCalcHome...,...,0.6468,0.1008,0.0086,0.2733,0.6386,0.0795,0.0237,0.3858,0.4081,0.1825
2646,201539,2140700,21407,Canton City Schools Adult Career and Technical...,Canton,OH,44710,Council on Occupational Education,https://www.ccsdistrict.org/domain/94,www.ccsdistrict.org/domain/94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1408,160612,202400,2024,Southeastern Louisiana University,Hammond,LA,70402,Southern Association of Colleges and Schools C...,www.southeastern.edu,www.southeastern.edu/admin/fin_aid/net_price_c...,...,0.4887,0.1973,0.0164,0.3569,0.4363,0.1904,0.013,0.455,0.2699,0.2621
819,139384,402400,4024,Georgia Northwestern Technical College,Rome,GA,30161,Southern Association of Colleges and Schools C...,www.gntc.edu,www.gntc.edu/npcalc/npcalc.htm,...,0.5496,0.4421,0.0094,0.0017,0.4509,0.538,0.0104,0.0019,0.3827,0.605
4933,441645,3626300,36263,Brown Aveda Institute-Mentor,Mentor,OH,44060,National Accrediting Commission of Career Arts...,WWW.BROWNAVEDA.COM,www.brownaveda.com/search?q=net%20price%20calc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
838,139995,1077100,10771,Gupton Jones College of Funeral Service,Decatur,GA,30035-4022,American Board of Funeral Service Education Co...,www.gupton-jones.edu/,www.gupton-jones.edu/admissions/general-info,...,NaN,NaN,0,0.1981,0.7358,0.066,NaN,NaN,NaN,NaN
4447,407683,2285901,22859,UCAS University of Cosmetology Arts & Sciences...,Harlingen,TX,78550-5034,National Accrediting Commission of Career Arts...,www.ucastx.com,www.ucastx.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3056,213826,329600,3296,Marywood University,Scranton,PA,18509-1598,Middle States Commission on Higher Education,www.marywood.edu/,www.marywood.edu/admissions/calc.html,...,0.6592,0.1741,0.0016,0.1986,0.6867,0.1131,0.0426,0.3404,0.1489,0.4681
3017,212975,2536600,25366,Commonwealth Technical Institute,Johnstown,PA,15905-3092,Accrediting Commission of Career Schools and C...,www.dli.pa.gov,dli.pa.gov/Individuals/Disability-Services/hga...,...,NaN,NaN,0,0,0.7698,0.2302,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
2441,196592,1014200,10142,Touro College,New York,NY,10018,Middle States Commission on Higher Education,www.touro.edu,www.touro.edu/students/net-price-calculators/,...,0.6536,0.1759,0.0212,0.2668,0.5348,0.1772,0.0433,0.1111,0.5838,0.2618
1753,173416,1040200,10402,Dakota County Technical College,Rosemount,MN,55068-2999,Higher Learning Commission,www.dctc.edu/,www.MinnState.edu/admissions/calculator/dakota...,...,0.5043,0.2564,0.0053,0.2153,0.4685,0.311,0.005,0.2544,0.3904,0.3501
3736,235167,815500,8155,The Evergreen State College,Olympia,WA,98505-0001,Northwest Commission on Colleges and Universities,www.evergreen.edu,www.evergreen.edu/costs/netprice-freshman.htm,...,0.7426,0.117,0.005,0.1935,0.674,0.1275,0.0125,0.1688,0.625,0.1938
1078,149842,396100,3961,William Rainey Harper College,Palatine,IL,60067-7398,Higher Learning Commission,https://www.harpercollege.edu/index.php,https://www.harpercollege.edu/gov/financialaid...,...,0.4175,0.2528,0.0165,0.3708,0.3575,0.2552,0.0145,0.2817,0.3257,0.3781
6115,480967,4224900,42249,College of the Muscogee Nation,Okmulgee,OK,74447-0917,Higher Learning Commission,cmn.edu,cmn.edu/NetPriceCalculator.html?authuser=0&fea...,...,0.4681,0.3404,0.0156,0.1094,0.4531,0.4219,0.0294,0.2059,0.3529,0.4118
594,129181,730306,7303,Lincoln Technical Institute-East Windsor,East Windsor,CT,06088,Accrediting Commission of Career Schools and C...,www.lincolntech.edu/campus/east-windsor-ct,www.lincolntech.edu/net-price-calculator,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1812,175078,237500,2375,Southwest Minnesota State University,Marshall,MN,56258-5468,Higher Learning Commission,www.smsu.edu,www.minnstate.edu/admissions/calculator/southw...,...,0.5333,0.2279,0.0152,0.314,0.4714,0.1994,0.005,0.2462,0.4925,0.2563
1049,148584,166400,1664,University of St Francis,Joliet,IL,60435-6188,Higher Learning Commission,www.stfrancis.edu,https://www.stfrancis.edu/admissions/financial...,...,0.6862,0.1607,0,0.2503,0.6856,0.0641,0.02,0.12,0.564,0.296
20,101295,787100,7871,George C Wallace State Community College-Hance...,Hanceville,AL,35077-2000,Southern Association of Colleges and Schools C...,www.wallacestate.edu,www.wallacestate.edu/Financial-Aid/Net-Price-C...,...,0.4286,0.2472,0.0084,0.2639,0.3458,0.3818,0.0103,0.374,0.2665,0.3492
2590,199971,3570300,35703,Carolina Christian College,Winston Salem,NC,27105,Association for Bibical Higher Educaiton,www.carolina.edu,www.carolina.edu/npcalc_000.htm,...,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN,NaN
4244,375568,3051500,30515,U S Grant Joint Vocational School,Bethel,OH,45106,Council on Occupational Education,www.grantcareer.com,www.grantcareer.com/npcalc/npcalc.htm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Read (with naked eyes, not computer) the dictionary and find out the definitions of the following 12 columns and copy the text next to the column name
- UNITID: (definition here) --the school ID          
- INSTNM:    Institution name     
- CITY:       city of the university/school               
- ZIP:        zip code     
- ADM_RATE:   Admission Rate      
- UGDS:        Number of undergraduate students      
- TUITIONFEE_IN:   In state Tuition fees      
- MN_EARN_WNE_P10: Money earned

In [12]:
# reimport the data with above 12 columns (ignore all other variables)
#(Write code here)

#creating a new dataframe df2 to include the above columns mentioned
column_list=['UNITID','INSTNM','CITY','ZIP','ADM_RATE','UGDS','TUITIONFEE_IN','MN_EARN_WNE_P10']
df2=dataframe[column_list]
print("The new dataframe is:")
print(df2)

The new dataframe is:
        UNITID                                             INSTNM  \
0       100654                           Alabama A & M University
1       100663                University of Alabama at Birmingham
2       100690                                 Amridge University
3       100706                University of Alabama in Huntsville
4       100724                           Alabama State University
...        ...                                                ...
7107  48312404                   Arizona State University at Yuma
7108  48387801  Bay Area Medical Academy - San Jose Satellite ...
7109  48400201                        High Desert Medical College
7110  48778201                                       BCI - Malden
7111  49005401          Health Career Institute- Lauderdale Lakes

                  CITY         ZIP  ADM_RATE     UGDS  TUITIONFEE_IN  \
0               Normal       35762    0.9027   4824.0         9857.0
1           Birmingham  35294-0110    0.9181  12866.0         8328.0
2           Montgomery  36117-3553       NaN    322.0         6900.0
3           Huntsville       35899    0.8123   6917.0        10280.0
4           Montgomery  36104-0271    0.9787   4189.0        11068.0
...                ...         ...       ...      ...            ...
7107              Yuma   853656900       NaN      NaN            NaN
7108          San Jose       95113       NaN      NaN            NaN
7109         Lancaster   935340000       NaN      NaN            NaN
7110            Malden   021480000       NaN      NaN            NaN
7111  Lauderdale Lakes   333137268       NaN      NaN        22575.0

      MN_EARN_WNE_P10
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
...               ...
7107              NaN
7108              NaN
7109              NaN
7110              NaN
7111              NaN

[7112 rows x 8 columns]

In [13]:
# Find out the 10 colleges that are hardest to get in (top 10)
#(Write code here)
top10 = df2.nlargest(10, "ADM_RATE") 
print("The 10 colleges that are hardest to get in ", top10)

The 10 colleges that are hardest to get in        UNITID                                      INSTNM        CITY  \
24    101453               Heritage Christian University    Florence
240   110918                California Christian College      Fresno
370   118161    Lytles Redwood Empire Beauty College Inc  Santa Rosa
472   123280    Shasta Bible College and Graduate School     Redding
559   127653                           Naropa University     Boulder
571   127954  Montessori Education Center of the Rockies     Boulder
652   131830      National Conservatory of Dramatic Arts  Washington
665   132842              Carlos Albizu University-Miami       Miami
887   142090                         Boise Bible College       Boise
1011  147165                            Midstate College      Peoria

             ZIP  ADM_RATE   UGDS  TUITIONFEE_IN  MN_EARN_WNE_P10
24    35630-9977       1.0   59.0        11232.0              NaN
240        93727       1.0   16.0         9330.0              NaN
370        95403       1.0  158.0            NaN              NaN
472        96002       1.0   42.0        12060.0              NaN
559   80302-6697       1.0  384.0        31790.0              NaN
571        80301       1.0   16.0            NaN              NaN
652        20007       1.0   32.0         9900.0              NaN
665   33172-2209       1.0  236.0        12444.0              NaN
887   83714-1220       1.0  128.0        12080.0              NaN
1011  61614-3595       1.0  274.0        16230.0              NaN

In [15]:
# 10. Find out the average in-state tuition of top 10
fees_top10=top10["TUITIONFEE_IN"].mean()
print("The average in-state tuition of top 10", fees_top10)
#(Write code here)

The average in-state tuition of top 10 14383.25

In [16]:
# Find out the average earnings of graduates from the top 10
earnings_top10=top10["MN_EARN_WNE_P10"].mean()
print("The average earnings of graduates from the top 10", earnings_top10)
#(Write code here)

The average earnings of graduates from the top 10 nan

In [17]:
# Find out the 10 colleges that are easiest to get in (bottom 10)

#(Write code here)

bottom10 = df2.nsmallest(10, "ADM_RATE")
print("Bottom 10 colleges are:", bottom10)

Bottom 10 colleges are:       UNITID                                             INSTNM  \
2974  211635                         Citizens School of Nursing
5226  448309  Shorter University-College of Adult & Professi...
6112  480912       Gemini School of Visual Arts & Communication
6664  491288             University of Wisconsin-Milwaukee Flex
2978  211893                          Curtis Institute of Music
3979  243744                                Stanford University
1557  166027                                 Harvard University
2302  192110                               The Juilliard School
2123  186131                               Princeton University
2233  190150        Columbia University in the City of New York

                CITY         ZIP  ADM_RATE    UGDS  TUITIONFEE_IN  \
2974  New Kensington  15068-6525    0.0000   158.0            NaN
5226            Rome       30165    0.0000   113.0         9680.0
6112      Cedar Park       78613    0.0000    18.0            NaN
6664       Milwaukee       53201    0.0000   501.0         6750.0
2978    Philadelphia       19103    0.0330   131.0         2675.0
3979        Stanford       94305    0.0473  7056.0        49617.0
1557       Cambridge       02138    0.0516  7532.0        48949.0
2302        New York  10023-6588    0.0592   486.0        43170.0
2123       Princeton  08544-0070    0.0641  5246.0        47140.0
2233        New York       10027    0.0661  8170.0        57208.0

      MN_EARN_WNE_P10
2974              NaN
5226              NaN
6112              NaN
6664              NaN
2978              NaN
3979              NaN
1557              NaN
2302              NaN
2123              NaN
2233              NaN

In [18]:
# Find out the average in-state tuition of the bottom 10
#(Write code here)
avg_bottom10_fees=bottom10["TUITIONFEE_IN"].mean()
print("The average in-state tuition of the bottom 10 is",avg_bottom10_fees)

The average in-state tuition of the bottom 10 is 33148.625

In [19]:
# Find out the average earnings of graduates from the bottom 10
#(Write code here)
avg_bottom10_earnings=bottom10["MN_EARN_WNE_P10"].mean()
print("The average earnings of graduates from the bottom 10", avg_bottom10_earnings)

The average earnings of graduates from the bottom 10 nan

#citation
#referred to the class lectures and notebooks
#https://www.geeksforgeeks.org/python-pandas-dataframe-nsmallest/
#https://stackoverflow.com/questions/15943769/how-do-i-get-the-row-count-of-a-pandas-dataframe
#https://www.geeksforgeeks.org/how-to-randomly-select-rows-from-pandas-dataframe/
#https://www.geeksforgeeks.org/how-to-select-multiple-columns-in-a-pandas-dataframe/
#https://stackoverflow.com/questions/58272872/pandas-top-10-values-of-every-item
#https://www.geeksforgeeks.org/python-pandas-dataframe-nlargest/
#https://stackoverflow.com/questions/31037298/pandas-get-column-average-mean